version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    command: 'npm start'
    ports:
      - 8080:8080
    environment:
      - PORT=8080
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
